import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      // Common
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'reset': 'Reset',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'home': 'Home',
      'rate_app': 'Rate App',
      'privacy_policy': 'Privacy Policy',
      'remove_ads': 'Remove Ads',
      'premium_title': 'Premium',
      'premium_subtitle': 'Remove ads, unlock all features, and stay focused.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'Remove ads',
      'premium_benefit_unlimited': 'Use all features without limits',
      'premium_benefit_statistics': 'View additional statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '1 week premium access',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days premium access',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days premium access',
      'premium_purchase': 'Start Premium',
      'premium_restore': 'Restore Purchase',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'If your payment is completed, purchase will be restored automatically after app restart.',
      'purchase_error': 'Purchase Error',
      'purchase_unavailable': 'In-app purchase is not available now.',
      'purchase_failed': 'Purchase failed. Please try again.',
      'restore_error': 'Restore failed. Please try again.',
      'purchase_success': 'Purchase Completed',
      'premium_ready': 'Premium is now active.',
      'send_feedback': 'Send Feedback',
      'more_apps': 'More Apps',
      'open_history': 'History',
      'open_stats': 'Stats',
      'clear_all': 'Clear All',
      'no_history': 'No history',
      'unknown_event': 'Unknown Event',
      'history_subtitle': 'Screen: @screen / Route: @route',
      'total_events': 'Total Events',
      'today_events': 'Today',
      'week_events': 'This Week',
      'unique_routes': 'Routes',
      'unique_screens': 'Screens',
      'top_events': 'Top Events',

      // App-specific
      'app_name': 'Tic-Tac-Toe & Gomoku',
      'tic_tac_toe': 'Tic-Tac-Toe',
      'gomoku': 'Gomoku',
      'game_type': 'GAME TYPE',
      'game_mode': 'MODE',
      'difficulty': 'DIFFICULTY',
      'vs_ai': 'vs AI',
      'vs_friend': 'vs Friend',
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard',
      'stats': 'STATS',
      'wins': 'Wins',
      'losses': 'Losses',
      'draws': 'Draws',
      'win_rate': 'Win rate',
      'no_games_yet': 'No games played yet',
      'start_game': 'Start Game',
      'restart': 'Restart',

      // Game status
      'your_turn': 'Your Turn',
      'ai_thinking': 'AI Thinking...',
      'p1_turn_x': 'Player 1 (X)',
      'p2_turn_o': 'Player 2 (O)',
      'p1_turn_b': 'Player 1 (Black)',
      'p2_turn_w': 'Player 2 (White)',
      'ready': 'Ready',
      'draw': 'Draw!',

      // Result
      'you_win': 'You Win!',
      'ai_wins': 'AI Wins',
      'p1_wins': 'Player 1 Wins!',
      'p2_wins': 'Player 2 Wins!',
      'beat_ai': 'Great job beating the AI!',
      'try_again': 'Better luck next time!',
      'well_played': 'Well played!',
      'close_game': "It's a close one!",
      'play_again': 'Play Again',

      // AI Upgrade
      'ai_upgrade_title': 'AI Upgraded!',
      'ai_upgrade_desc': 'AI will play at Hard difficulty for the next game.',
      'ai_upgraded_badge': '⚡ AI Upgraded (Hard)',
      'ai_upgrade_banner_title': 'Upgrade AI to Hard',
      'ai_upgrade_banner_desc': 'Watch an ad to make AI use max difficulty for 1 game.',
    },
    'ko': {
      // 공통
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'delete': '삭제',
      'edit': '편집',
      'reset': '초기화',
      'done': '완료',
      'ok': '확인',
      'yes': '예',
      'no': '아니요',
      'error': '오류',
      'home': '홈',
      'rate_app': '앱 평가',
      'privacy_policy': '개인정보처리방침',
      'remove_ads': '광고 제거',
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 제거, 추가 기능 잠금 해제, 끊김 없는 이용을 제공합니다.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '추가 통계 보기',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일 프리미엄',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일 프리미엄',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일 프리미엄',
      'premium_purchase': '구매하기',
      'premium_restore': '구매 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_error': '구매 오류',
      'purchase_unavailable': '인앱 결제를 사용할 수 없어요.',
      'purchase_failed': '결제에 실패했어요. 다시 시도해요.',
      'restore_error': '구매 복원에 실패했어요.',
      'purchase_success': '결제 완료',
      'premium_ready': '프리미엄이 활성화됐어요.',
      'send_feedback': '피드백 보내기',
      'more_apps': '더 많은 앱',
      'open_history': '히스토리',
      'open_stats': '통계',
      'clear_all': '전체 삭제',
      'no_history': '기록이 없습니다',
      'unknown_event': '알 수 없는 이벤트',
      'history_subtitle': '화면: @screen / 경로: @route',
      'total_events': '총 이벤트',
      'today_events': '오늘',
      'week_events': '이번 주',
      'unique_routes': '고유 경로',
      'unique_screens': '고유 화면',
      'top_events': '상위 이벤트',
      // 앱 전용
      'app_name': '틱택토 & 오목',
      'tic_tac_toe': '틱택토',
      'gomoku': '오목',
      'game_type': '게임 유형',
      'game_mode': '모드',
      'difficulty': '난이도',
      'vs_ai': 'AI 대전',
      'vs_friend': '친구 대전',
      'easy': '쉬움',
      'medium': '보통',
      'hard': '어려움',
      'stats': '통계',
      'wins': '승',
      'losses': '패',
      'draws': '무',
      'win_rate': '승률',
      'no_games_yet': '아직 게임 기록이 없습니다',
      'start_game': '게임 시작',
      'restart': '재시작',
      // Game status
      'your_turn': '당신의 차례',
      'ai_thinking': 'AI 생각 중...',
      'p1_turn_x': '플레이어 1 (X)',
      'p2_turn_o': '플레이어 2 (O)',
      'p1_turn_b': '플레이어 1 (흑)',
      'p2_turn_w': '플레이어 2 (백)',
      'ready': '준비',
      'draw': '무승부!',
      // Result
      'you_win': '당신이 이겼어요!',
      'ai_wins': 'AI 승리',
      'p1_wins': '플레이어 1 승리!',
      'p2_wins': '플레이어 2 승리!',
      'beat_ai': 'AI를 이겼어요!',
      'try_again': '다음번엔 잘 할 수 있어요!',
      'well_played': '잘 하셨어요!',
      'play_again': '다시 하기',

      // AI 업그레이드
      'ai_upgrade_title': 'AI 업그레이드!',
      'ai_upgrade_desc': '다음 1판에서 AI가 최고 난이도로 플레이합니다.',
      'ai_upgraded_badge': '⚡ AI 업그레이드됨 (하드)',
      'ai_upgrade_banner_title': 'AI를 최고 난이도로 업그레이드',
      'ai_upgrade_banner_desc': '광고 시청 시 다음 1판에서 AI가 최고 난이도로 동작합니다.',
    },
  };
}



